Don't give out password length in logs
DbUp/DbUp pull request #604
Opened 2022-02-08 20:28 UTC by amosonn

2022-02-10 11:22 UTC, AdrianJSClark requested changes
Such a simple change. After seeing it I'm not sure why it was done the complicated way to begin with!

If you fix up those extra semi-colons & the build passes I'm happy to merge.

2022-02-10 11:22 UTC, AdrianJSClark commented on src/dbup-postgresql/PostgresqlExtensions.cs
> +            logMasterConnectionStringBuilder.Password = "******";
```suggestion
            logMasterConnectionStringBuilder.Password = "******"
```
Small typo on these three lines, which is why the build failed. I'll add suggestions to the others as well, so you can quickly fix them.

2022-02-14 04:31 UTC, amosonn commented on src/dbup-sqlserver/SqlServerExtensions.cs
> +            Password = "******";
I'm pretty sure only this one is wrong, the other two are fine. Updated the commit.

2022-02-14 04:46 UTC, merged

2022-02-14 04:46 UTC, AdrianJSClark commented
Thanks, @amosonn!